# Pandas - Conceptual & Technical Assessment

### Section A – Output Prediction

##### Q1. Array operations and vectorization

```python
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)
```

**Predicited Output:**
[20, 40, 60]
| Index | Value |
|:------|:------|
| 0 | 20 |
| 1 | 40 |
| 2 | 60 |

Explanation: The output is [20, 40, 60] because arr * 2 performs a vectorized operation, multiplying each element in the NumPy array by 2. A Pandas Series behaves similarly: it multiplies each value by 2 while preserving the Series index.


In [1]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

display(arr * 2)
display(s * 2)


[20 40 60]
0    20
1    40
2    60
dtype: int64


##### Q2. Boolean filtering

```python
df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})
result = df[df['Marks'] >= 65]
print(result[['Student', 'Marks']])
```
**Predicted Output:**
|   | Student | Marks |
|:--------|:--------|:------|
|1|B|80|
|2|C|65|
|3|D|90|

**Explanation:**
The condition df['Marks'] >= 65 checks the Marks column.The rows that satisfy this condition are displayed in the output.


In [2]:
df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})
result = df[df['Marks'] >= 65]
display(result[['Student', 'Marks']])


  Student  Marks
1       B     80
2       C     65
3       D     90


##### Q3. Descriptive statistics

```python
df = pd.DataFrame({'Marks': [10, 20, 30, 40, 50]})
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

```
**Predicted Output:**
30
50
30

**Explanation:**
`.mean()`,`.median()`,and`.mode()` are statistical methods that return the mean (average), median, and mode of a column. When applied to the Marks column, they return a mean of 30, a median of 30, and a mode of 10, 20, 30, 40, and 50, since every value appears once.

In [3]:
df = pd.DataFrame({'Marks': [10, 20, 30, 40, 50]})
print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0


##### Q4. Group-wise analysis

```python
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})
print(df.groupby('Department')['Salary'].mean())
```
**Predicted output:**

| Department | Mean Salary |
|:------------|:------------|
| HR | 40000 |
| IT | 50000 |

**Explanation:** The `.groupby()` method groups rows that have the same value. Since we are grouping by `Department`, the rows are split into the HR and IT groups.The mean salary for each department is then calculated and displayed.


In [4]:
df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})
print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64


##### Q5. Positive correlation

```python
df = pd.DataFrame({'Hours': [1, 2, 3, 4], 'Marks': [20, 40, 60, 80]})
print(df['Hours'].corr(df['Marks']))
```
**Predicted output:**
1


**Explanation:**
Correlation measures the linear relationship between two columns. A value closer to -1 indicates a stronger negative relationship, while a value closer to 1 indicates a stronger positive relationship. A value near 0 indicates little or no linear relationship between the columns. 

In [5]:
df = pd.DataFrame({'Hours': [1, 2, 3, 4], 'Marks': [20, 40, 60, 80]})
print(df['Hours'].corr(df['Marks']))

1.0


##### Q6. Negative correlation

```python
df = pd.DataFrame({'Price': [10, 20, 30, 40], 'Demand': [100, 80, 60, 40]})
print(df['Price'].corr(df['Demand']))
```
**Predicted output:**
-1



**Explanation:**
A negative correlation means that as one variable increases, the other tends to decrease. The coefficient ranges from 0 to -1: values closer to -1 indicate a stronger negative relationship, while values closer to 0 indicate a weaker negative relationship. A coefficient of 0 indicates no linear relationship.


In [6]:
df = pd.DataFrame({'Price': [10, 20, 30, 40], 'Demand': [100, 80, 60, 40]})
print(df['Price'].corr(df['Demand']))

-1.0


### Section B

##### Q1. JSON & CSV

### Given Code:
```python
import pandas as pd

df = pd.read_csv("students.csv", header=None)
print(df)    
```
NOTE: A CSV file contains a header row, but the following code incorrectly reads the first student's record as column names. Correct the code


**Error-Explanation:** `header=None` tells Pandas that the CSV file has no header row. However, the file does contain a header, so this setting causes Pandas to treat the header row as data instead of using it for the column names.

### Corrected Code :
```python
import pandas as pd

df = pd.read_csv("students.csv")
print(df)


##### Q2. Display five highest salaries

### Given Code:
```python
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary').head(5))                              
```
The objective is to display the five highest salaries from a DataFrame. Correct the code.


**Error-Explanation:**
`sort_values('Salary')` sorts the salaries in ascending order by default, so `.head(5)` selects the five lowest salaries. To display the five highest salaries, sort in descending order by setting `ascending=False

### Corrected Code :


```python
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))
```

##### Q3. Fill missing marks

### Given Code:
```python
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'].fillna(df['Marks'].mean())
print(df)    
```
A student wants to replace missing marks with the column's mean but writes code that does not update the DataFrame. Correct the code.

**Error-Explanation:**
`df['Marks'].fillna(df['Marks'].mean())` creates a Series with the missing value replaced, but the result is not assigned back to the DataFrame. Therefore, `df` remains unchanged when it is printed. Assign the result back to `df['Marks']` to update the column

### Corrected Code :
```python
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df) 
```


##### Q4. Correlation

### Given Code:
```python
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df.corr('Hours', 'Marks'))
```

The objective is to calculate the correlation between Hours and Marks. Correct the code.

**Error-Explanation:** `DataFrame.corr()` does not accept column names as its first two positional arguments. Selecting both columns first and then calling `.corr()` calculates their pairwise correlations.

### Corrected Code:
```python
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))
```

### Section C

##### Q1. NumPy broadcasting

In [1]:
import numpy as np

a = np.array([[10], [20], [30]]) 
b = np.array([[1, 2, 3]])         
result = a + b
print("Result:\n", result)
print("Shape:", result.shape)

b2 = np.array([1, 2])
try:
    result2 = a + b2
    print("\nWith b = np.array([1, 2]):")
    print(result2)
    print("Shape:", result2.shape)
except ValueError as e:
    print("\nValueError with b = np.array([1, 2]):", e)


Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape: (3, 3)

With b = np.array([1, 2]):
[[11 12]
 [21 22]
 [31 32]]
Shape: (3, 2)


**Predicted Output:**
```
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Shape: (3, 3)
```

**Explanation:**

1. `a` has shape (3, 1) and `b` has shape (1, 3). NumPy compares shapes right-to-left and stretches any dimension of size 1 to match the other, yielding a (3, 3) output — an outer-sum of all row–column pairs.
2. This differs from adding two 1-D arrays of shape (3,), where elements are matched positionally (index-to-index), giving only 3 values instead of 9.
3. With `b = np.array([1, 2])` (shape (2,)), NumPy aligns it as (1, 2) against `a`'s (3, 1): dimension 0 stretches `b` → 3, dimension 1 stretches `a` → 2, producing shape (3, 2) with no error.
4. A `ValueError` would only occur if neither dimension is 1 (e.g., `a` shape (3,1) + `b` shape (2,2)), since 3 and 2 are incompatible and cannot be broadcast.


##### Q2. CSV parsing, missing values, and dates

In [8]:
import pandas as pd
from io import StringIO

csv_text = '''ID,Name,Date,Marks
101,"Asha, R",2026-09-01,80
102,Ravi,01/09/2026,
103,Neha,2026-09-03,NA
'''

df = pd.read_csv(
    StringIO(csv_text),
    na_values=["NA", ""],         
    keep_default_na=True
)
print("── Raw load ──")
display(df)
print()
print("dtypes after raw load:")
display(df.dtypes)

df["Date"] = pd.to_datetime(df["Date"], dayfirst=False, format="mixed")

print("\n── Missing Marks (investigate before dropping) ──")
display(df[df["Marks"].isna()])

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print("\n── Cleaned DataFrame ──")
display(df)
print()
print("dtypes after cleaning:")
display(df.dtypes)


── Raw load ──
    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  01/09/2026    NaN
2  103     Neha  2026-09-03    NaN

dtypes after raw load:
ID         int64
Name         str
Date         str
Marks    float64
dtype: object

── Missing Marks (investigate before dropping) ──
    ID  Name       Date  Marks
1  102  Ravi 2026-01-09    NaN
2  103  Neha 2026-09-03    NaN

── Cleaned DataFrame ──
    ID     Name       Date  Marks
0  101  Asha, R 2026-09-01   80.0
1  102     Ravi 2026-01-09   80.0
2  103     Neha 2026-09-03   80.0

dtypes after cleaning:
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object


**Predicted Output:**
```
    ID     Name        Date  Marks
0  101  Asha, R  2026-09-01   80.0
1  102     Ravi  2026-01-09    NaN
2  103     Neha  2026-09-03    NaN

dtypes after cleaning:
ID                int64
Name                str
Date     datetime64[us]
Marks           float64
```

**Explanation:**

1. `pd.read_csv()` follows the RFC 4180 standard and treats text inside double-quotes as a single field, so the comma in `"Asha, R"` is not split — it is read correctly as one value in the Name column.
2. The Date column contains two formats (YYYY-MM-DD and DD/MM/YYYY); without `pd.to_datetime(..., format="mixed")` the column stays as plain string (object dtype), making date arithmetic and filtering impossible.
3. Both a blank entry and the string "NA" are converted to NaN using `na_values=["NA", ""]`; however, "NA" must be investigated before treating it as missing — it may mean "Not Assessed" or "Not Applicable" rather than a genuinely absent value, and dropping it blindly could remove a valid record.
4. After parsing, missing Marks are filled with the column mean as a safe placeholder; in practice the correct action (fill, drop, or flag) should be decided only after understanding why each value is missing.


##### Q3. Salary outlier and robust summary

In [9]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary":   [25000, 30000, 35000, 10000000]
})

mean_salary   = df["Salary"].mean()
median_salary = df["Salary"].median()

print(f"Mean   Salary : {mean_salary:,.2f}")
print(f"Median Salary : {median_salary:,.2f}")

highest_paid = df[df["Salary"] == df["Salary"].max()]
print("\n── Highest-paid employee record ──")
display(highest_paid)

mean_without_outlier = df[df["Salary"] < 10000000]["Salary"].mean()
print(f"\nMean without outlier : {mean_without_outlier:,.2f}")
print(f"Mean with    outlier : {mean_salary:,.2f}")
print(f"Difference           : {mean_salary - mean_without_outlier:,.2f}")

print(f"\nMedian better represents a typical salary: {median_salary:,.2f}")


Mean   Salary : 2,522,500.00
Median Salary : 32,500.00

── Highest-paid employee record ──
  Employee    Salary
3        D  10000000

Mean without outlier : 30,000.00
Mean with    outlier : 2,522,500.00
Difference           : 2,492,500.00

Median better represents a typical salary: 32,500.00


**Predicted Output:**
```
Mean   Salary : 2,522,500.00
Median Salary :    32,500.00

Highest-paid employee record:
  Employee    Salary
3        D  10000000

Mean without outlier : 30,000.00
Mean with    outlier : 2,522,500.00
Difference           : 2,492,500.00

Median better represents a typical salary: 32,500.00
```

**Explanation:**

1. The mean is (25000 + 30000 + 35000 + 10000000) / 4 = 2,522,500 and the median is the average of the two middle values (30000 + 35000) / 2 = 32,500.
2. The extreme salary of 10,000,000 pulls the mean up by over 2.4 million, making it far higher than three of the four actual salaries and an unreliable measure of central tendency for this dataset.
3. The median (32,500) is the better representative of a typical employee's salary because it is unaffected by extreme values and sits within the realistic range of the other three salaries (25,000–35,000).
4. Employee D's record must be investigated before removal — the value could be a legitimate executive salary, a data-entry error (extra zeros), or a unit mismatch (e.g., rupees vs dollars); removing it without verification risks deleting a real and important record.


### Section D – Scenario-based problem (8 marks)


##### Q1. Clean student assessment data 

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_assessment.csv", dtype=str)
print("-- head() --")
display(df.head())
print("\n-- info() --")
df.info()
print("\n-- isnull().sum() --")
print(df.isnull().sum())
rows_loaded = len(df)

dept_map = {
    "it":      "IT",
    "i.t.":    "IT",
    "finance": "Finance",
    "hr":      "HR",
}
df["Department"] = df["Department"].str.strip().str.lower().map(dept_map)
print("\n-- Department value counts after standardization --")
print(df["Department"].value_counts())

before_dedup = len(df)
df = df.drop_duplicates()
duplicates_removed = before_dedup - len(df)
print(f"\nDuplicates removed : {duplicates_removed}")

df["Absent_Flag"] = df["Marks"].str.strip().str.lower() == "absent"

df["Marks"] = (
    df["Marks"]
    .str.extract(r"(\d+\.?\d*)", expand=False)
)
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

print("\n-- Marks after parsing --")
display(df[["Student_ID", "Student_Name", "Marks", "Absent_Flag"]])

absent_students = df[df["Absent_Flag"]]
unentered_marks = df[~df["Absent_Flag"] & df["Marks"].isna()]

print(f"\nAbsent students ({len(absent_students)}):")
display(absent_students[["Student_ID", "Student_Name"]])

print(f"\nUnentered marks ({len(unentered_marks)}):")
display(unentered_marks[["Student_ID", "Student_Name"]])

invalid_marks = df[df["Marks"].notna() & ((df["Marks"] < 0) | (df["Marks"] > 100))]
print(f"\nInvalid marks outside 0-100 ({len(invalid_marks)}):")
display(invalid_marks[["Student_ID", "Student_Name", "Marks"]])

print("\n== Cleaned DataFrame ==")
display(df[["Student_ID", "Student_Name", "Department", "Marks", "Absent_Flag"]])

print("\n== Summary Report ==")
print(f"  Records loaded              : {rows_loaded}")
print(f"  Duplicates removed          : {duplicates_removed}")
print(f"  Records after dedup         : {len(df)}")
print(f"  Absent students             : {len(absent_students)}")
print(f"  Unentered marks (NaN)       : {len(unentered_marks)}")
print(f"  Invalid marks (outside 0-100): {len(invalid_marks)}")


-- head() --


,Student_ID,Student_Name,Department,Assessment,Marks
0,S101,Asha,IT,Python,85
1,S102,Ravi,it,Python,78
2,S103,Neha,I.T.,Python,92
3,S104,Karan,HR,Python,NaN
4,S105,Meera,HR,Python,Absent



-- info() --
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes

-- isnull().sum() --
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64

-- Department value counts after standardization --
Department
IT         7
HR         4
Finance    4
Name: count, dtype: int64

Duplicates removed : 1

-- Marks after parsing --
   Student_ID Student_Name  Marks  Absent_Flag
0        S101         Asha   85.0        False
1        S102         Ravi   78.0        False
2        S103         Neha   92.0        False
3        S104        Karan    NaN        False
4        S105        Meera 

**Cleaning Decisions, Results, and Justification:**

1. **Load & Inspect** — The dataset is loaded with `dtype=str` so every value is read as plain text, preventing Pandas from silently converting `"88 marks"` or `"Absent"` to `NaN`. `head()`, `info()`, and `isnull().sum()` are used to inspect structure and missing values before cleaning.

2. **Standardize Departments** — A lowercase-lookup dictionary maps `it`, `i.t.` → `IT` and `finance` → `Finance` using `.str.lower().map(dept_map)`, making the logic explicit and consistent across all casing variants.

3. **Remove Duplicates** — `drop_duplicates()` removes rows where every column is identical. The record `(S102, Ravi, it, Python, 78)` appeared twice and was reduced to one; records sharing a Student_ID but with different marks are retained.

4. **Parse Marks** — `"88 marks"` is cleaned using regex to extract the numeric part; `"Absent"` is flagged in an `Absent_Flag` column before conversion; `"NA"` and blanks become `NaN` via `pd.to_numeric(..., errors="coerce")`.

5. **Absence vs Unentered** — S105 (Meera) is marked `Absent` (did not sit the assessment); S104 (Karan), S109 (Sneha), and S112 (Aman) have blank entries (marks not yet recorded). **Risk:** Dropping all `NaN` rows without investigation silently removes absent students, shrinking the cohort and making pass rates appear artificially higher.

6. **Out-of-Range Marks** — S114 (Kabir) has a mark of `105`, which exceeds the valid range of 0–100. This must be verified against the source record before correction or removal — it could be a data-entry error (e.g., `95` mistyped as `105`).

**Summary Report:**

| Metric | Count |
|--------|-------|
| Records loaded | 15 |
| Duplicates removed | 1 |
| Records after dedup | 14 |
| Absent students | 1 |
| Unentered marks (NaN) | 3 |
| Invalid marks (outside 0–100) | 1 |
